version: "3.8"
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:1.23.10
    restart: always
    volumes:
      - ./uptime-kuma:/app/data
    ports:
      - "3001:3001"

networks:
  default:
    name: network-stack