name: "deploy-dev-website"

on:
  push:
    branches:
      - main
    paths:
      - "**"
      - ".github/workflows/webportal-server-prod.yaml"

jobs:
  
  deploy:
    
    name: Build Image
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
          host: ${{ secrets.REMOTE_HOST_PROD }}
          username: ${{ secrets.REMOTE_USER_PROD }}
          key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
          port: 22  
          command_timeout: 200m
          script: | 
              cd smartcbt-webportal
              git pull         
              rm -rf .env
              cat > .env << EOF
              ${{ vars.ENV_PROD }}
              EOF
              cd /home/ubuntu/
              docker compose -f smartcbt-webportal/docker-compose.yml up -d --build

    - name: Google Chat Notification
      uses: Co-qn/google-chat-notification@releases/v1
      with:
        name: Build
        url: ${{ secrets.PROD_GOOGLE_CHAT_WEBHOOK }}
        status: ${{ job.status }}
      if: always()